name: Score-Manager-Web-Page-Deploy

on:
  push:
   branches:
    - web

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: deploy Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .